name: CI

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs_version:
          - 29.1

    steps:
    - name: Install zsh
      run: "sudo apt-get install -y zsh && zsh --version"

    - name: Install fish
      run: 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)" && brew install -q fish && fish --version'

    - name: Set up Emacs
      uses: jcs090218/setup-emacs@master
      with:
        version: ${{matrix.emacs_version}}

    - name: Install Eldev
      uses: emacs-eldev/setup-eldev@v1

    - name: Check out the source code
      uses: actions/checkout@v4

    - name: Install Sphinx
      run: 'pip3 install -r docs/requirements.txt'

    - name: Re-build mistty.texi
      run: 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)" && eldev build --force mistty.texi'

    - name: Update mistty.texi
      # Only run on main branch push (e.g. after pull request merge).
      if: github.event_name == 'push'
      run: |
        if git diff -s --exit-code mistty.texi; then
          echo "mistty.texi not modified by this commit"
        else
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add mistty.texi
          git commit -m "Auto-update mistty.texi" --author "${{ env.CI_COMMIT_AUTHOR }}"
          git push
        fi

    - name: Test the project
      run: 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)" && eldev -p -dtT test --ci'
