name: CI

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs_version:
          - 29.1

    steps:
    - name: Install Nix and set up Emacs
      uses: jcs090218/setup-emacs@master
      with:
        version: ${{matrix.emacs_version}}

    - name: Install Test dependencies
      run: |
        nix profile install nixpkgs/b833ff01a0d694b910daca6e2ff4a3f26dee478c#zsh
        nix profile install nixpkgs/b833ff01a0d694b910daca6e2ff4a3f26dee478c#fish
        nix profile install nixpkgs/b833ff01a0d694b910daca6e2ff4a3f26dee478c#vim
        nix profile install nixpkgs/566e53c2ad750c84f6d31f9ccb9d00f823165550#python311Packages.ipython

    - name: Install Eldev
      uses: emacs-eldev/setup-eldev@v1

    - name: Check out the source code
      uses: actions/checkout@v4

    - name: Install Sphinx
      run: |
        nix profile install nixpkgs/b833ff01a0d694b910daca6e2ff4a3f26dee478c#texinfo
        pip3 install -r docs/requirements.txt

    - name: Re-build mistty.texi
      run: 'eldev build --force mistty.texi'

    - name: Update mistty.texi
      # Only run on main branch push (e.g. after pull request merge).
      if: github.event_name == 'push'
      run: |
        if git diff -s --exit-code mistty.texi; then
          echo "mistty.texi not modified by this commit"
        else
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add mistty.texi
          git commit -m "Auto-update mistty.texi" --author "${{ env.CI_COMMIT_AUTHOR }}"
          git push
        fi

    - name: Test the project
      run: 'eldev -p -dtT test --ci'
