name: CI

on:
  push:
    paths-ignore:
      - '**.md'
      - 'docs/**'
  pull_request:
    paths-ignore:
      - '**.md'
      - 'docs/**'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs_version:
          - 29.1
          - 29.4
          - 30.1

    steps:
    - name: Install Nix and set up Emacs
      uses: jcs090218/setup-emacs@master
      with:
        version: ${{matrix.emacs_version}}

    - name: Install Test dependencies
      run: |
        nix profile install nixpkgs/8a2f738d9d1f1d986b5a4cd2fd2061a7127237d7#zsh
        nix profile install nixpkgs/8a2f738d9d1f1d986b5a4cd2fd2061a7127237d7#fish
        nix profile install nixpkgs/8a2f738d9d1f1d986b5a4cd2fd2061a7127237d7#vim
        nix profile install nixpkgs/566e53c2ad750c84f6d31f9ccb9d00f823165550#python311Packages.ipython

    - name: Install Eldev
      uses: emacs-eldev/setup-eldev@v1

    - name: Check out the source code
      uses: actions/checkout@v4

    - name: Test the project
      run: 'eldev -p -dtT test --ci || eldev -p -dtT test --ci :failed'
